name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  changelog-update: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Merge') && contains(github.event.head_commit.message, 'history')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Changelog Update
        id: release_version
        run: |
          file_name="CHANGELOG.md"

          if [ -s "$file_name" ]; then
            version=$(head -n 1 $file_name)
            version_number=$(echo "$version" | sed 's/[^0-9.]//g')
            version_minor_number=$(echo "$version" | awk -F '.' '{print $2}')
            version_minor_next_version=$((version_minor_number + 1))
            version_final=$(echo "$version_number" | sed "s/\([0-9]\.\)$version_minor_number/\1$version_minor_next_version/")
            version_final_formated=$(echo "v$version_final")

            echo "$version_final"

            histories_log=$(cat histories)
            histories_new_log=$(echo "# v$version_final\n\n## Alterações\n$histories_log\n---\n\n")
            histories_old=$(cat $file_name)
            printf "$histories_new_log$histories_old" > $file_name
            truncate -s 0 histories

            echo "::set-output name=RELEASE_VERSION::$(echo $version_final_formated)"
          else
            printf "# v1.0.0\n\n## Alterações\n" > "$file_name"
            cat histories >> "$file_name"
            printf "\n---" >> "$file_name"
            truncate -s 0 histories
            echo "::set-output name=RELEASE_VERSION::$(echo 'v1.0.0')"
          fi

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          BRANCH_NAME="main"
          git add .
          git commit -m "Update file via API"
          git push origin $BRANCH_NAME

      - name: Create Release
        run: |
          git checkout -b release/${{ steps.release_version.outputs.RELEASE_VERSION }}
          git push origin release/${{ steps.release_version.outputs.RELEASE_VERSION }}
