name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
