name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'history/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Title PR
        id: get_message
        run: echo "::set-output name=MESSAGE::$(echo '${{github.event.head_commit.message}}' | tail -n 1)"

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=BRANCH_REF::$(echo ${GITHUB_REF#refs/})"

      - name: Test
        run: |
          echo ${{ steps.get_message.outputs.MESSAGE }} >> histories
          git add histories
          git commit -m "action: update histories logs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
