name: History Log

on:
  workflow_dispatch:
  push:
    branches:
      - 'history/*'

jobs:
  typer-history:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Merge')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Get Title PR
        id: get_message
        run: echo "::set-output name=MESSAGE::$(echo '${{github.event.head_commit.message}}' | tail -n 1)"

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=BRANCH_REF::$(echo ${GITHUB_REF#refs/})"

      - name: Test
        run: |
          echo "- ${{ steps.get_message.outputs.MESSAGE }}" >> histories

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes